version: 2
jobs:
  go:1.8:
    docker:
      - image: circleci/golang:1.8
      - image: circleci/mysql:latest
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD=true
          - MYSQL_DATABASE=xorm_test
          - MYSQL_USER=root
      - image: postgres:latest
        environment:
        - POSTGRES_DB=xorm_test
    working_directory: /go/src/github.com/go-xorm/xorm
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            go get -v -t -d ./...
      - run:
          name: Build
          command: go build -race .
      - run:
          name: Test mysql
          command: |
            go test -v -race -db="mysql" -conn_str="root:@/xorm_test"
            go test -v -race -db="mysql" -conn_str="root:@/xorm_test" -cache=true
      - run:
          name: Test postgres
          command: |
            go test -v -race -db="postgres" -conn_str="dbname=xorm_test sslmode=disable"
            go test -v -race -db="postgres" -conn_str="dbname=xorm_test sslmode=disable" -cache=true
      - run:
          name: Test sqlite3
          command: |
            go test -v -race -db="sqlite3" -conn_str="./test.db"
            go test -v -race -db="sqlite3" -conn_str="./test.db" -cache=true
  go:latest:
    docker:
      - image: circleci/golang:latest
      - image: circleci/mysql:latest
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD=true
          - MYSQL_DATABASE=xorm_test
          - MYSQL_USER=root
      - image: postgres:latest
        environment:
        - POSTGRES_DB=xorm_test
    working_directory: /go/src/github.com/go-xorm/xorm
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            go get -v -t -d ./...
      - run:
          name: Build
          command: go build -race .
      - run:
          name: Test mysql
          command: |
            go test -v -race -db="mysql" -conn_str="root:@/xorm_test"
            go test -v -race -db="mysql" -conn_str="root:@/xorm_test" -cache=true
      - run:
          name: Test postgres
          command: |
            go test -v -race -db="postgres" -conn_str="dbname=xorm_test sslmode=disable"
            go test -v -race -db="postgres" -conn_str="dbname=xorm_test sslmode=disable" -cache=true
      - run:
          name: Test sqlite3
          command: |
            go test -v -race -db="sqlite3" -conn_str="./test.db"
            go test -v -race -db="sqlite3" -conn_str="./test.db" -cache=true

workflows:
  version: 2
  build_and_test:
    jobs:
      - go:1.8
      - go:latest
